version: "2"
services:
  zabbix-server-mysql:
    image: centos/mysql-57-centos7
    container_name: zabbix-mysql
    ports:
      - "3306:3306"
    volumes:
      - /data/scripts/zabbix/mysql/:/var/lib/mysql/:rw
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=zabbix
  zabbix:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/scripts/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /data/scripts/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
    links:
      -  zabbix-server-mysql:db
    environment:
      - MYSQL_USER=zabbix
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_PASSWORD=123456

  nginx:
    image: zabbix/zabbix-web-nginx-mysql
    container_name: zabbix-nginx
    ports:
      - "8443:443"
      - "8000:80"
    links:
      - zabbix-server-mysql:db
      - zabbix:server
    environment:
      - MYSQL_USER=zabbix
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_PASSWORD=123456
      - PHP_TZ=Asia/Shanghai
      - ZBX_SERVER_HOST=server
